name: cinefetch
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  dio: ^5.4.3+1
  retrofit: ^4.2.0
  json_annotation: ^4.9.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^9.1.3
  build_runner: ^2.4.9
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true